spring:
  main:
    allow-circular-references: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    username: root
    password: root.
    url: jdbc:mysql://localhost:3306/testdb
  flyway:
    baseline-on-migrate: true
server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always